### ISSUE TITLE
Ionic 3 - Can't get android contact photo

### ISSUE THREAD

**Issue by DydjyZ** [apache/cordova-plugin-contacts#165]
There is some days that i search a solution to my problem.

I use the Ionic Contacts plugin ( https://ionicframework.com/docs/native/contacts/ ) and i need to get the photos of my contact list. In iOS it work but in android it won't.

I tried to sanitize,normalizeURL, and all that i found on the internet but it won't work.

Here's my code ;

home.ts

```
userPhoto: any;
  getContacts() {
    this.contacts.find(['displayName', 'name', 'phoneNumbers', 'emails', 'photos'], {filter: "", multiple: true})
        .then(data => {
          console.table(data[0]);
          this.userName = data[0].displayName;
          this.userPhoto = this.sanitizer.bypassSecurityTrustUrl(data[0].photos[0].value);
        });
  }
```
home.html

```
  <button ion-button (click)="getContacts()">Get contacts</button>

  <p>Nom : {{ userName }}</p>

  <hr />
  <img [src]="userPhoto" style="width: 100px;">
```

The error that i got in Chrome inspector:

`Not allowed to load local resource: content://com.android.contacts/contacts/1/photo`

Does you have any solution ?

Thanks you,

Dylan

**Comment by janpio** [comment]
Here is some code that definitely used to work: https://github.com/janpio/ionic-native-contacts/blob/master/src/pages/home/home.ts#L29

**Comment by janpio** [comment]
What is your `ionic info` output?
Did you download the app I linked to, install it and run it with the configuration there is?

**Comment by DydjyZ** [comment]
Here's my ionic info :

`✔ Gathering environment info - done!

Ionic:

   ionic (Ionic CLI)  : 4.1.1 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.0

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.0.0
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.2, cordova-plugin-ionic-webview 2.1.0, (and 6 other plugins)

System:

   ios-deploy : 1.9.2
   NodeJS     : v8.9.3 (/usr/local/bin/node)
   npm        : 5.6.0
   OS         : macOS High Sierra
   Xcode      : Xcode 9.4.1 Build version 9F2000`

I just saw when i download your code and start into my smartphone the app, it work, but when I copy the home.ts/.html code into my app, it won't work... 

I didn't see any difference between these two apps except there is not the same version of ionic..

**Comment by janpio** [comment]
Compare `ionic cordova platform list`, `ionic cordova plugin list` and `package.json` in total.

**Comment by DydjyZ** [comment]
I think it's not a plugin error because it's a blank projets.. so I anyway inspect the plugins and there is no difference between the two apps except the ionic version..

**Comment by janpio** [comment]
Your `ionic info` output shows `cordova-plugin-ionic-webview 2.1.0` which did not exist back when I created the demo repository.

**Comment by DydjyZ** [comment]
Hello,

Thanks you it effectively was the cordova-plugin-ionic-webview plugin, when i removed it it worked  !

Thanks you ou saved me a lot of time 👍 

Dylan

**Comment by Pezhvak** [comment]
i tried everything i just removed the webview plugin as well. can't make it to work

**Comment by 1AbhinavMaurya** [comment]
yup i also tried everything but img is not display
