### ISSUE TITLE
undefined is not an object while calling 

### ISSUE THREAD

**Issue by candradeg9182** [apache/cordova-plugin-contacts#167]
Hi, I have an error when trying to call contacts.create.

This is the error in the console. 
"Ionic Native: tried calling Contacts.create, but the Contacts plugin is not installed"

And the image is the error in the phone.

![contactsphoneerror](https://user-images.githubusercontent.com/10950629/44836820-363b6700-abf5-11e8-9f35-cceb1537f828.png)

code:
![contactocodigo](https://user-images.githubusercontent.com/10950629/44837700-8b787800-abf7-11e8-8b70-450a139b18ee.png)

Ionic:

   ionic (Ionic CLI)  : 4.1.1 (C:\Users\Claudio\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.0

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 6.4.0, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.2, (and 6 other plugins)

System:

   NodeJS : v8.11.3 (C:\Program Files\nodejs\node.exe)
   npm    : 6.1.0
   OS     : Windows 10

and a fraction of the angular.json

  "dependencies": {
    "@agm/core": "^1.0.0-beta.3",
    "@angular/animations": "5.2.11",
    "@angular/common": "5.2.11",
    "@angular/compiler": "5.2.11",
    "@angular/compiler-cli": "5.2.11",
    "@angular/core": "5.2.11",
    "@angular/forms": "5.2.11",
    "@angular/http": "5.2.11",
    "@angular/platform-browser": "5.2.11",
    "@angular/platform-browser-dynamic": "5.2.11",
    "@ionic-native/barcode-scanner": "^4.12.0",
    "@ionic-native/contacts": "^4.12.0",
    "@ionic-native/core": "~4.12.0",
    "@ionic-native/in-app-browser": "^4.12.0",
    "@ionic-native/splash-screen": "~4.12.0",
    "@ionic-native/status-bar": "~4.12.0",
    "@ionic/storage": "2.1.3",
    "angular2-google-maps": "^0.17.0",
    "cordova-android": "^7.1.1",
    "cordova-ios": "4.5.5",
    "cordova-plugin-contacts": "^3.0.1",
    "cordova-plugin-device": "^2.0.2",
    "cordova-plugin-inappbrowser": "^3.0.0",
    "cordova-plugin-ionic-keyboard": "^2.1.2",
    "cordova-plugin-splashscreen": "^5.0.2",
    "cordova-plugin-whitelist": "^1.3.3",
    "ionic-angular": "3.9.2",
    "ionicons": "3.0.0",
    "phonegap-plugin-barcodescanner": "^8.0.0",
    "rxjs": "5.5.11",
    "sw-toolbox": "3.6.0",
    "zone.js": "0.8.26"
  },
  "devDependencies": {
    "@ionic/app-scripts": "3.2.0",
    "typescript": "~2.6.2"
  },
  "description": "An Ionic project",
  "cordova": {
    "plugins": {
      "phonegap-plugin-barcodescanner": {},
      "cordova-plugin-inappbrowser": {},
      "cordova-plugin-contacts": {},
      "cordova-plugin-whitelist": {},
      "cordova-plugin-device": {},
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-ionic-keyboard": {}

**Comment by janpio** [comment]
You notice how even the error message begins with "Ionic Native"?

As the plugin is obviously installed:

>  "cordova-plugin-contacts": "^3.0.1",
> ...
> "cordova-plugin-contacts": {},

This clearly is not a bug with the plugin but with a) the Ionic Native wrapper or b) something that you are doing.

Please use https://github.com/ionic-team/ionic-native/issues/ or https://forum.ionicframework.com/
