### ISSUE TITLE
How to update existing contacts 

### ISSUE THREAD

**Issue by landry161** [apache/cordova-plugin-contacts#168]
Someone can help me. How to update an existing contacts ?

**Comment by janpio** [comment]
`find` first, then make your changes and then `save` on the `Contact`: https://github.com/apache/cordova-plugin-contacts#methods-1

**Comment by landry161** [comment]
Ok thanks for the answers. It works fine but the displyName does not change

**Comment by Bramzor** [comment]
> `find` first, then make your changes and then `save` on the `Contact`: https://github.com/apache/cordova-plugin-contacts#methods-1

This is not correct. Save will only update things like name/notes etc. If you for example want to add phoneNumber, Email, Addresses etc, this apparently will not work with save() unless you clone first but than information which is not cloned can be lost.

**Comment by janpio** [comment]
> this apparently will not work with save() unless you clone first but than information which is not cloned can be lost.

Huh what?

**Comment by timbru31** [comment]
We are archiving this repository following [Apache Cordova's Deprecation Policy](https://cordova.apache.org/deprecation_policy.html). We will not continue to work on this repository. Therefore all issues and pull requests are being closed. Thanks for your contribution.
