### ISSUE TITLE
Add created and updated date to contacts

### ISSUE THREAD

**Issue by rhanesoghlyan** [apache/cordova-plugin-contacts#169]
For fetching contact list in my app I need get created and updated date for each contact.

**Comment by janpio** [comment]
This is not one (or two) of the Contact's properties per the documentation:
https://github.com/apache/cordova-plugin-contacts#properties

Is this available in native code? Then it could theoretically, maybe added to the plugin via a PR.

**Comment by rhanesoghlyan** [comment]
Yes in native side it is possible. I think that is an important information about each contact. 

With the help of the plugin  I can see only this information: 
![screenshot from 2018-09-20 14-26-52](https://user-images.githubusercontent.com/22957192/45812789-d6ab1580-bce1-11e8-9b6a-96ea298ace2c.png)

**Comment by janpio** [comment]
... which corresponds to the documentation I linked to above.

If the data is available on all relevant platforms, we are of course open to a Pull Request that adds this information to the `Contact` model.

**Comment by rhanesoghlyan** [comment]
Thanks for clarification.

**Comment by rhanesoghlyan** [comment]
@janpio I've tested in iOS and Android platforms. iOS has provided as created and updated date. But in Android it doesn't work. But we have a solution which get us info when contact list has been updated. 

So solution is: 
We will generate hash code based on contact list data. So this hash will be updated when contact list has been changed. 

What do you think about this solution?

**Comment by janpio** [comment]
Ok, did I understand correctly?

a)
On iOS you can get `updateAt` and `createdAt` for a contact.
On Android you can _not_ get this information for a contact.

b)
You also want to generate a hash on the whole contact list. If one contact changes, the hash will also change. Correct?

How are a and b connected?

**Comment by rhanesoghlyan** [comment]
Yes, It's correct. 

We can add functionality for generating hash with contact list data. 
So when contact list will be changed hash code will also change

**Comment by janpio** [comment]
I don't see how this is connected to a).

**Comment by rhanesoghlyan** [comment]
For now I have a problem to define whether the contacts have been updated or created. I wanted to implement the functionality of getting the updated date of the contacts in order to define whether some of the contacts has been changed. As now the Android is not giving the possibility to get the created and updated date we decided to generate hash with contact list data. So in app we can compare between the hash received from plugin and the hash received before that. By using this functionality we can understand if the contact list  have been changed.

**Comment by janpio** [comment]
Ah ok, you didn't mention your original goal before.

You should create a new issue for that one and start it with the intention of creating a hash over all contacts - then we can discuss there.

**Comment by rhanesoghlyan** [comment]
So I will open

**Comment by janpio** [comment]
(I reopened this issue - although _you_ do not need this functionality, it is a valid enhancement request that I might want to have open for now)

**Comment by timbru31** [comment]
We are archiving this repository following [Apache Cordova's Deprecation Policy](https://cordova.apache.org/deprecation_policy.html). We will not continue to work on this repository. Therefore all issues and pull requests are being closed. Thanks for your contribution.
