### ISSUE TITLE
Add hash with all contact list

### ISSUE THREAD

**Issue by rhanesoghlyan** [apache/cordova-plugin-contacts#170]
Now I have a problem to define whether the contacts have been updated or created. I wanted to implement the functionality of getting the updated date of the contacts in order to define whether some of the contacts has been changed. As now the Android is not giving the possibility to get the created and updated date we decided to generate hash with contact list data. So in app we can compare between the hash received from plugin and the hash received before that. By using this functionality we can understand if the contact list have been changed.

**Comment by janpio** [comment]
So you need something like a `getLastUpdateToAllContacts`?

**Comment by rhanesoghlyan** [comment]
Yes, something like that.

**Comment by janpio** [comment]
Using a hash over all contacts sounds like a doable but not very simple and conservative solution.

I remember there was a fork of this plugin that added a "subscription" for changes on contacts, but I am not sure if this functionality was for iOS, Android or both. You would have to search for it yourself.

In general I think even if you implement the hash method, this is nothing that should be part of the plugin itself but live in your app itself. Feel free to share your code here though, maybe someone else might find it useful as well!

**Comment by Bramzor** [comment]
Hi @rhanesoghlyan , the way we keep track of these updated contacts is by adding an url to the contact which holds this information including a timestamp and we also keep hashes but we currently keep this hash outside the contact itself.

So we would indeed like something simular (preferably a tag that is even only visible for a specific app) and maybe this is possible with iOS with the new Contacts SDK.
Currently we are stuck however on a save() bug that is in this plugin and currently trying to fix this plugin bug first.

**Comment by rhanesoghlyan** [comment]
Yes @Bramzor before implementing new features in contacts plugin you need fix current bugs :) 
Also find method doesn't work as expected in iOS 11-12 versions. I've checked codes and there are a lot of deprecated methods had been used. 
For using this plugin we need update 70% of code :)

**Comment by Bramzor** [comment]
What is wrong with the find method? It works on iOS11 in the emulator here. Yes the SDK calls are deprecated but they currently do still work as far as I was able to test them.

**Comment by Bramzor** [comment]
Can you create an issue for this and explain with code examples that it does not return all contacts in the emulator?

**Comment by timbru31** [comment]
We are archiving this repository following [Apache Cordova's Deprecation Policy](https://cordova.apache.org/deprecation_policy.html). We will not continue to work on this repository. Therefore all issues and pull requests are being closed. Thanks for your contribution.
