### ISSUE TITLE
App crashes on ANDROID 8 version 

### ISSUE THREAD

**Issue by rhanesoghlyan** [apache/cordova-plugin-contacts#173]
During creating contact on Samsung S8(Android version 8.0.0) App crashes

**Comment by duncan-c** [comment]
This is to do with the way that Android now handles app permissions. I've forked the repository and updated the [https://github.com/duncan-c/cordova-plugin-contacts/blob/master/src/android/ContactManager.java](ContactManager.java) file to fix the issue.
It seems to work fine for me now - however I haven't been able to debug it on an earlier version of Android yet (but don't see any reason for it not to work).

**Comment by Bramzor** [comment]
If I read between the lines, your crash is related to not asking permission to access the contacts first right?

**Comment by janpio** [comment]
@duncan-c Please open a PR that contributes your changes back to this repository if you didn't do so yet. Thanks.

**Comment by duncan-c** [comment]
Have done now. I wasn't sure if I should as the plugin is marked as deprecated.

**Comment by OmarHassan25** [comment]
@duncan-c updated ContactManager.java solves the problem

**Comment by D4rkMindz** [comment]
When is the PR going to be merged?

**Comment by oscardavidiaz** [comment]
I'm waiting too :(

**Comment by timbru31** [comment]
We are archiving this repository following [Apache Cordova's Deprecation Policy](https://cordova.apache.org/deprecation_policy.html). We will not continue to work on this repository. Therefore all issues and pull requests are being closed. Thanks for your contribution.
