### ISSUE TITLE
how to get recent contacts from cordova  contacts plugin

### ISSUE THREAD

**Issue by chowdarycss** [apache/cordova-plugin-contacts#175]
is their any possibilities to get recent contacts from ionic cordova contacts plugin

**Comment by Bramzor** [comment]
Recent as in last created or last updated? This is currently not possible as no creation/update date is kept. What you might do is just ordering and filtering on ID but that will only work for creation and is a dirty method as you can specify an id if you create a user as far as I know so its not correct in all cases. But it might be good enough for your usecase.

**Comment by timbru31** [comment]
We are archiving this repository following [Apache Cordova's Deprecation Policy](https://cordova.apache.org/deprecation_policy.html). We will not continue to work on this repository. Therefore all issues and pull requests are being closed. Thanks for your contribution.
