### ISSUE TITLE
Save to sim card

### ISSUE THREAD

**Issue by f18nfz** [apache/cordova-plugin-contacts#178]
How can we create the contact to the sim card instead of the phone?

**Comment by janpio** [comment]
As the README of the plugin doesn't mention `SIM` once, this is probably not possible.

**Comment by Bramzor** [comment]
@f18nfz On which platform would you like this? Because I do not see this happen on iOS for example.

**Comment by f18nfz** [comment]
> @f18nfz On which platform would you like this? Because I do not see this happen on iOS for example.

Wanted to see this on Android

**Comment by timbru31** [comment]
We are archiving this repository following [Apache Cordova's Deprecation Policy](https://cordova.apache.org/deprecation_policy.html). We will not continue to work on this repository. Therefore all issues and pull requests are being closed. Thanks for your contribution.
