### ISSUE TITLE
There is no Neighborhood filed in the address in cordova plugin contacts

### ISSUE THREAD

**Issue by Ghayyas** [apache/cordova-plugin-contacts#183]
Hi, Im working on cordova plugin contacts. But I see there is no neighborhood filed in the address array. How Can I add Neighborhood filed in contact list.

**Comment by janpio** [comment]
What is a "neighborhood filed"? 
If you mean "neighborhood field", does this exist in both Android and iOS?
Should it be part of the `[ContactAddress](https://github.com/apache/cordova-plugin-contacts#contactaddress)`?

**Comment by Ghayyas** [comment]
Yes It should be. Neighborhood field is just like a field in address like phone number adress etc.

**Comment by timbru31** [comment]
We are archiving this repository following [Apache Cordova's Deprecation Policy](https://cordova.apache.org/deprecation_policy.html). We will not continue to work on this repository. Therefore all issues and pull requests are being closed. Thanks for your contribution.
