### ISSUE TITLE
List contact on phone was empty after update contact

### ISSUE THREAD

**Issue by danbeo95** [apache/cordova-plugin-contacts#184]
I try update one contact on my phone by call save() method.But after update i refresh my contact on phone.It was empty.Please hep me!

**Comment by timbru31** [comment]
We are archiving this repository following [Apache Cordova's Deprecation Policy](https://cordova.apache.org/deprecation_policy.html). We will not continue to work on this repository. Therefore all issues and pull requests are being closed. Thanks for your contribution.
