### ISSUE TITLE
New (Capacitor) contacts plugin to solve deprecated status 

### ISSUE THREAD

**Issue by Bramzor** [apache/cordova-plugin-contacts#185]
As you all know, this plugin was deprecated and no further development or bugfixing will be done. This is a major issue for everyone who uses this plugin which is a lot of people.

Now their might be a solution, but it all depends on you guys.
Capacitor is creating a list of plugins they will write and all they needs is a thumbs up from you guys to prioritize this plugin!
https://github.com/ionic-team/capacitor/issues/799

What is Capacitor? Its a way to include native code into your hybrid app (a bit like cordova does but better).

Help us with your thumbs up: https://github.com/ionic-team/capacitor/issues/799

**Comment by janpio** [comment]
Important to know: Capacitor is a replacement for Cordova built by Ionic.
You will not be able to use this new Capacitor plugin with Cordova apps, just with Capacitor apps.

**Comment by Bramzor** [comment]
However, some Cordova plugins can still be used by Capacitor.
@janpio thanks for the clarification.

**Comment by janpio** [comment]
Yes, Cordova plugins can be used with Capacitor (as they built this to be able to benefit from all the existing Cordova plugins - smart move). The reverse is not true for Capacitor plugins in Cordova.

If this could even be possible would depend on how the Capacitor plugin is implemented. Some of the native functionality is integrated in Capacitor itself as "APIs", I haven'T seen to many really external plugins for it yet. Could those maybe somehow be integrated in Cordova apps @jcesarmobile?

**Comment by Bramzor** [comment]
Good point. If cordova could benefit from the plugins written for Capacitor (or the other frameworks), all the better. Seems a lot of cordova plugins can use some maintenance done by the other frameworks anyway. For me personally it does not matter that much, but in the end we really needed to solve this deprecated plugin.
And yes, it is a bit of advertising for a solution of the competition but as the current solution is no more, the community needs an alternative anyway. I do not have any relations with Capacitor whatsoever, but it seems that it might be a solution to this specific issue.

**Comment by janpio** [comment]
Yeah, the "problem" here is that is not a "solution for the community", but an invitation to change communities ;) 

I, as a Cordova committer, would greatly prefer a new Cordova plugin for contact management. 
I, as a Ionic user, don't really care if I package my app with Cordova or Capacitor.

I'll let the issue live a bit here, hope it gives a few +1 to the issue over there.

**Comment by jcesarmobile** [comment]
I'll suggest you to look on the network tab to see other active forks https://github.com/apache/cordova-plugin-contacts/network

The plugin was deprecated by Cordova committers because the main goal of Cordova Core plugins was to be replaced by the browser implementation once the vendors catch up, but contacts API was discontinued by W3C, so we did the same.

This only mean Cordova committers will not take care of the plugin anymore, but anybody can fork it and maintain it.
