### ISSUE TITLE
 Access to contact lists on phone it was very slow after call save Method !

### ISSUE THREAD

**Issue by danbeo95** [apache/cordova-plugin-contacts#187]
Please support me ! When i call save() method to modify contact.It was sccucess.But i notify ,after that access to contact lists on phone it was very slow .How can i fix it ?

**Comment by danbeo95** [comment]
@janpio can you support me ?

**Comment by janpio** [comment]
No. (Don't mention people to pull them into your issue. If someone wants to respond, they will.)

**Comment by timbru31** [comment]
We are archiving this repository following [Apache Cordova's Deprecation Policy](https://cordova.apache.org/deprecation_policy.html). We will not continue to work on this repository. Therefore all issues and pull requests are being closed. Thanks for your contribution.
