### ISSUE TITLE
Spaces in Contact Phone Number are breaking search filter

### ISSUE THREAD

**Issue by joeldhenry** [apache/cordova-plugin-contacts#188]
Finding a contact by phoneNumbers will not return the contact unless filter string is identical to contact phone number:

Example: filter: '049999111' **will** return contact with phone number '0499991111' 
however
Example: filter: '049999111' **will not** return contact with phone number '04 9999 1111' 
Example: filter: '04 9999 111' **will not** return contact with phone number '0499991111' 

Example: filter: '9111' **will** return contact with phone number '0499991111' 
however
Example: filter: '9111' **will not** return contact with phone number '04 9999 1111' 

Since the phone number is unknown what format it will be in, the spacing should be disregarded 

Cordova 7.1.0
Cordova iOS 4.5.5
iOS 12.1 iPhone X

**Comment by joeldhenry** [comment]
Temporarily I have transformed my filter searches to be in the format of "123 123 123" to fix the spaces interfering with my search's

**Comment by joeldhenry** [comment]
update: also seems that phone numbers in iOS 11 have no-break spaces instead of regular spaces, which also does not find contacts, i cannot repeat this in iOS 12 though.

**Comment by timbru31** [comment]
We are archiving this repository following [Apache Cordova's Deprecation Policy](https://cordova.apache.org/deprecation_policy.html). We will not continue to work on this repository. Therefore all issues and pull requests are being closed. Thanks for your contribution.
