### ISSUE TITLE
How to Link contacts 

### ISSUE THREAD

**Issue by rahuljograna** [apache/cordova-plugin-contacts#198]
how can I link contact like in Native Contact application?

**Comment by janpio** [comment]
What exactly do you want to do?

**Comment by rahuljograna** [comment]
iOS 10+ introduces the concept of linked contacts, in which individual contacts can be grouped into a unified contact (like a view). The Cordova Contacts plugin retrieves individual contacts only whereas on iOS the Contacts framework retrieve these unified contacts. The plugin "find" method should imitate the native Contacts framework behaviour and return grouped contacts. For Android, the plugin should imitate the native behaviour as well, if applicable.

**Comment by janpio** [comment]
I don't see anything in the documentation about this, so this probably hadn't been implemented before the plugin was deprecated.

**Comment by janpio** [comment]
No idea, sorry.

If an API for this exists, of course one could implement it as a new plugin or add it to this plugin - but as I said it is deprecated so the Cordova team won't do that.

**Comment by rahuljograna** [comment]
Ok @janpio , thanks for this

**Comment by Bramzor** [comment]
This plugin is based on the old AddressBook SDK which is deprecated starting from iOS9. I assume you are referring to a feature in the new SDK so in that case, it is not supported.

**Comment by timbru31** [comment]
We are archiving this repository following [Apache Cordova's Deprecation Policy](https://cordova.apache.org/deprecation_policy.html). We will not continue to work on this repository. Therefore all issues and pull requests are being closed. Thanks for your contribution.
