### ISSUE TITLE
Can not delete address from contact information Android.

### ISSUE THREAD

**Issue by rahuljograna** [apache/cordova-plugin-contacts#200]
I have more than three address in single contact and I want to remove (delete) one of address from the list, how can I do this??

**Comment by Bramzor** [comment]
Just find contact and if you have contact object, do contact.remove()

**Comment by timbru31** [comment]
We are archiving this repository following [Apache Cordova's Deprecation Policy](https://cordova.apache.org/deprecation_policy.html). We will not continue to work on this repository. Therefore all issues and pull requests are being closed. Thanks for your contribution.
