### ISSUE TITLE
Contact updates of the arrays (phoneNumbers, addresses, urls) ignored on iOS

### ISSUE THREAD

**Issue by Bramzor** [apache/cordova-plugin-contacts#201]
I tried updating contact information on iOS using the plugin and it worked for strings but once I tried to modify array types, it was actually just ignored in the update.
After searching a bit further, I noticed that when I did put a breakpoint in the ios code, it worked but when removing that breakpoint again, it failed. Which made me conclude that its some kind of race condition.
Now I wonder if this issue is Ionic related or not. Not that Ionic does a lot with the contacts itself, it basically just allows Typescripting etc.

Anyone using this plugin with Ionic which notices the same issues?

**Comment by ppetree** [comment]
If you look at the iOS log files I bet you will find a bunch of deprecation notices. Scan for CDVcontact.h and you'll find a whole bunch of stuff was deprecated starting with iOS9.0 and the authors of this never thought of updating this stuff when iOS 9.0 was released back in 2015.

**Comment by Bramzor** [comment]
Currently there is no alternative so we are stuck with it and I'm pretty sure its a small issue as I found out that it works when I place a breakpoint in the native code so it seems some kind of race condition. So thats not related to all the deprecation notices or old code, it's just a bug.

**Comment by Bramzor** [comment]
But no one that uses this plugin and modifies these arrays just to confirm they have the same behavior on iOS?

**Comment by ppetree** [comment]
This plugin is not returning email addresses on iOS 11.x (haven't tested on 9/10/12 yet) and seems to be ignoring that little part where it just returns the fields you want.

@janpio Yeah, buy me a nice new Macbook Pro, install xCode and get Cordova apps compiling (for both platforms) and then ship the box to me and I'll fix all those niggling little bugs. ;-)  Until then, I think the project I'm investigating may be my first Flutter project.

**Comment by Bramzor** [comment]
> This plugin is not returning email addresses on iOS 11.x (haven't tested on 9/10/12 yet) and seems to be ignoring that little part where it just returns the fields you want.

Think you might be doing something wrong. Just checked logs and I do get email addresses on iOS 11.2 , same for iOS 12.1 . The problem is not retrieving information because all of that works. It is just when you try to UPDATE an array these updates are just ignored when I run it without a breakpoint. I work around the issue currently by removing a contact and inserting a clone of that contact again but I can only do that for new contacts as the clone itself might not have all the information the contact had. 

So conclusion is that UPDATE functionality is currently broken in the plugin on iOS (havent tested it specifically on Android). Combination CREATE & REMOVE works but not ideal. We really need to get it fixed.

**Comment by ppetree** [comment]
Ok, I'll double check what I'm doing in my code... I don't need to update any information, just let grandma and grandpa pick their next of kin.

**Comment by timbru31** [comment]
We are archiving this repository following [Apache Cordova's Deprecation Policy](https://cordova.apache.org/deprecation_policy.html). We will not continue to work on this repository. Therefore all issues and pull requests are being closed. Thanks for your contribution.
