### ISSUE TITLE
Permission is not getting in ios

### ISSUE THREAD

**Issue by kalaiprakash93** [apache/cordova-plugin-contacts#202]
In iphone6,2 , device version : 12.1 
contact permission is not getting..

**Comment by Bramzor** [comment]
You need to ask permissions first. You can use the cordova diagnostics plugin for that.

**Comment by timbru31** [comment]
We are archiving this repository following [Apache Cordova's Deprecation Policy](https://cordova.apache.org/deprecation_policy.html). We will not continue to work on this repository. Therefore all issues and pull requests are being closed. Thanks for your contribution.
