### ISSUE TITLE
Not working when there are more than one contacts apps

### ISSUE THREAD

**Issue by ktsour** [apache/cordova-plugin-contacts#203]
We have a Samsung Galaxy S9 and it has two contacts apps. It lets us choose which app, then it shows the list of contacts, but when we select a contact, the result is "OPERATION_CANCELLED_ERROR".

More specifically, the second app is the app "Drupe". If we select a default contacts app, everything works fine.

**Comment by sabrinapisol** [comment]
I'm facing the same problem, did you find any solution?

**Comment by timbru31** [comment]
We are archiving this repository following [Apache Cordova's Deprecation Policy](https://cordova.apache.org/deprecation_policy.html). We will not continue to work on this repository. Therefore all issues and pull requests are being closed. Thanks for your contribution.
