### ISSUE TITLE
Deprecation notices iOS 9

### ISSUE THREAD

**Issue by Bramzor** [apache/cordova-plugin-contacts#204]
I was wondering what happens if Apple forces users to use the newer SDK from XCode 10. Do we still get these deprecation notices or cant we use this existing plugin anymore starting from Match?

**Comment by timbru31** [comment]
We are archiving this repository following [Apache Cordova's Deprecation Policy](https://cordova.apache.org/deprecation_policy.html). We will not continue to work on this repository. Therefore all issues and pull requests are being closed. Thanks for your contribution.
