### ISSUE TITLE
ionic contacts error: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by Robenalam** [apache/cordova-plugin-contacts#205]
let options = new ContactFindOptions();
  options.filter='';
  options.hasPhoneNumber=true;
  options.multiple=true;
  let contact:Contact[];
  this.contacts.find(["displayName","phoneNumbers"],options).then((cont)=>{
    contact=cont
  })

Ionic:

   ionic (Ionic CLI)  : 4.1.2 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.1

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.3.2, (and 14 other plugins)

System:

   ios-deploy : 2.0.0
   NodeJS     : v8.12.0 (/usr/local/bin/node)
   npm        : 6.4.1
   OS         : macOS
   Xcode      : Xcode 9.4.1 Build version 9F2000

Error:
vendor.js:1774 ERROR TypeError: Cannot read property 'split' of undefined
    at get (vendor.js:71544)
    at getPlugin (vendor.js:71576)
    at checkAvailability (vendor.js:112501)
    at vendor.js:72133
    at Contacts.find (vendor.js:72140)
    at OrderPage.webpackJsonp.390.OrderPage.ionViewDidLoad (main.js:1729)
    at ViewController._lifecycle (vendor.js:22559)
    at ViewController._didLoad (vendor.js:22442)
    at Tab.NavControllerBase._didLoad (vendor.js:55759)
    at t.invoke (polyfills.js:3)

**Comment by omazim** [comment]
Did you get this resolved? If so, how? I get the same error.

**Comment by ychaika** [comment]
Any updates?

**Comment by tntkhang** [comment]
As mention solution on this [link](https://stackoverflow.com/questions/53467337/error-typeerror-cannot-read-property-split-of-undefined-cordova-plugin-contac) let down the lastest version to 3.0.0 will solve it.

**Comment by timbru31** [comment]
We are archiving this repository following [Apache Cordova's Deprecation Policy](https://cordova.apache.org/deprecation_policy.html). We will not continue to work on this repository. Therefore all issues and pull requests are being closed. Thanks for your contribution.
