### ISSUE TITLE
Contact loading too slow when user has more than 3000 contacts in his phone.

### ISSUE THREAD

**Issue by vc-hitesh** [apache/cordova-plugin-contacts#206]
I am facing the issue on Android and IOS both platform that. If the user has a large number of the contact. The phone is stuck and time taking on load contact. Is any other way that I can get only updated or new added contact from the phone book.

**Comment by janpio** [comment]
Not with this plugin.

Are there native APIs to achieve this?

**Comment by vc-hitesh** [comment]
No, Not using API.

Only when the user has more than 3000 contacts in the phone book and tries to get the full list in the application at that time I am facing this issue.

Is there any way to improve the performance of import contact ?

**Comment by Bramzor** [comment]
Cordova people will not work on this plugin anymore so the only alternative would be that people from ionic capacitor would create their own plugin that has the same functionality so we could all migrate to capacitor.

**Comment by PragatiRode** [comment]
I am facing the loading contact more than 3500 issue on Android and IOS both platform.
is there any alternative?

**Comment by Bramzor** [comment]
What you can try is by trying to load in smaller batches? So a contact search which will return a batch and on a later time or even directly after the first load, a second, third, ... Difficulty here is that you want to make sure you do not load a contact more than once.

**Comment by PragatiRode** [comment]
Hi ,
Thanks for your reply,

I am new in ionic, i have to make an application which first show all
contact than can select multiple contact
Can you help me for that
I have fetched all contact using find method but it has contacts more than
4000 it will take time to load contact

**Comment by Bramzor** [comment]
@PragatiRode Do you really need to load the 4000 contacts or are these 4000 contacts on Android which are automatically created by gmail? You can skip these by only loading contacts with a phonenumber so you would avoid loading all 4000.

**Comment by PragatiRode** [comment]
Hi ,
We are making an application both for Android and iOS platform, in which we
are doing booking for customers which add passenger manually or from
contact list, for contact I have used cordova-plugin-contacts, but I am
facing problem for both platform. For Android, it shows me
unsorted,repeated phone numbers and loading problem. For iOS, it shows me
unsorted and loading problem. And one more problem is customer should able
to multiple selection. How can I solve this problem?

**Comment by PragatiRode** [comment]
Hi,
Plz help me out for solving the above issue

**Comment by Bramzor** [comment]
Sorting you should do after loading the contacts by simply using array sorting (so not in scope of the plugin).
Repeated phonenumbers depends on local contacts, probably they do exist multiple times in your local contacts and in that case you need to filter out the duplicates yourself.
Selection of multiple contacts, that is also something you need to develop outside the plugin.

**Comment by vc-hitesh** [comment]
Is there any way that application auto sync with the phonebook. That if user added new contact its automatically added to the application contact list.

**Comment by Pakyyy** [comment]
This plugin really take some time to load if you are reading a large amount of contact, as it convert all the information in the contact to a dictionary and transfer from native side to Cordova. (Tested on my own iOS device loading 2000+ contact required like 90s)

Sadly there is not much we can do, I would suggest to read those necessary field ONLY using options.desiredFields
for example:
`var options      = new ContactFindOptions();
options.desiredFields = [navigator.contacts.fieldType.name, navigator.contact. phoneNumbers]; // read only those you want to display`

which will greatly improve the loading time (in my case loading 2000+ contact in less that a second).

**Comment by breautek** [comment]
Thank you @Pakyyy for providing a workaround.

I agree, with what you said that there isn't much that can be done when it comes to large contact listings. Using the `desiredFields` to only include the fields you need for listing is probably the best approach. You can also probably make use of the `filter` field to fetch more detailed information for a specific contact when needed as well.

I don't think there is anything to be done here from Cordova's side, so I'll be closing this issue as "Won't fix"
