### ISSUE TITLE
All the fields are giving null value but count is correct. Ionic 4.

### ISSUE THREAD

**Issue by kiranp1992** [apache/cordova-plugin-contacts#207]

**Comment by janpio** [comment]
You should talk to the Ionic (Native) people then. The plugin obviously didn't change when Ionic 4 was released, and it worked with Ionic v3.

**Comment by AbhijeetFarakate** [comment]
**Check this out:**
[https://forum.ionicframework.com/t/getting-count-of-contacts-correct-but-getting-null-values-for-contacts-in-ionic-4/155987/4](url)
