### ISSUE TITLE
modify the contact picture 

### ISSUE THREAD

**Issue by VikasKad** [apache/cordova-plugin-contacts#208]
# Feature Request

## Motivation Behind Feature

As we are creating the phone contact manger module, we want to set users profile picture.

## Feature Description

As currently we are able to store all users details but we are not able to store the contact photo, my code is as follows:

`            contact.photos= [new ContactField('photo', this.tempProfilepic)];
`
where tempProfilePic is filePath URL, also I tried with base64 as well but nothing worked,
Might be the solution already available but I am not able to find it out properly.

Thanks in advance.

**Comment by Bramzor** [comment]
This is how I do it: `contact.photos.push(new ContactField(null, this.photo, true))` . where this.photo is just a publicly available picture url.

**Comment by VikasKad** [comment]
Finally Fixed with following code:

          contact.photos = [];
          contact.photos.push(new ContactField('photo', this.tempProfilepic, true))
Thanks @Bramzor for help
