### ISSUE TITLE
conduct contact.save() twice on Android, but only get one contact.

### ISSUE THREAD

**Issue by guanyuan** [apache/cordova-plugin-contacts#210]
# Bug Report

## Problem
I conduct contact.save() twice on android.
contact1 and contact2 are the same expect that they have different comany name.

### What is expected to happen?
I expect to get two contact on my phone, which is contact1 and contact2.

### What does actually happen?
I only get contact1 on my phone.
**But on IOS, I actually get two contacts.**

I am using cordova-plugin-contacts of version "2.3.1"

Can someone help?

**Comment by Bramzor** [comment]
Did you create a clone before saving or do they have the same rawId? Because save() is also used to update contacts.

**Comment by guanyuan** [comment]
I finally solved this issue by modify  line 1761 of ContactAccessorySDK5.java.
Just add below line:
.withValue(ContactsContract.RawContacts.AGGREGATION_MODE, ContactsContract.RawContacts.AGGREGATION_MODE_DISABLED)


I was inspired by: https://blog.csdn.net/windmxf/article/details/46053851

**Comment by janpio** [comment]
Nice! Can you create a pull request to the code here so other people can discover this change more easily? That would be awesome.
