### ISSUE TITLE
Plugin skip birthday without year on android

### ISSUE THREAD

**Issue by AlexanderVagner** [apache/cordova-plugin-contacts#213]
# Bug Report

## Problem
Contact with birthday, which is without year imports with empty birthday

### What is expected to happen?
Expects to have contact with birthday with empty year

### What does actually happen?
We have contact with empty birthday

## Information
<img width="958" alt="1b590002111100020000888800000000" src="https://user-images.githubusercontent.com/12045521/59938994-3bf18a00-945f-11e9-9bb0-c51ed5cc7b6d.png">

This problem is because date without year in android passed as "--MM-DD"(https://stackoverflow.com/questions/25161485/is-the-mm-dd-format-for-month-day-part-of-iso-8601), which cannot parse by `Date.valueOf` method.

### Environment, Platform, Device
Reproduced on Android 26 Pixel Emulator

## Checklist

- [ x] I searched for existing GitHub issues
- [x ] I updated all Cordova tooling to most recent version
- [ x] I included all the necessary information above

**Comment by timbru31** [comment]
We are archiving this repository following [Apache Cordova's Deprecation Policy](https://cordova.apache.org/deprecation_policy.html). We will not continue to work on this repository. Therefore all issues and pull requests are being closed. Thanks for your contribution.
