### ISSUE TITLE
Best approach for searching on phone number

### ISSUE THREAD

**Issue by andersborgabiro** [apache/cordova-plugin-contacts#215]
# Feature Request

## Motivation Behind Feature

The rationale for a best effort approach is e.g. reading up SMSs as "An SMS from Jim Smith: bla bla bla".

## Feature Description

A method for searching for phone numbers that given any compressed number (no white space) but with or without country code provide a safe method for getting search hits.

## Alternatives or Workarounds

Currently I do this, but it's not very safe:
    loosify(_number.substring(3))
where loosify inserts "%" like "%1%2%3%4%". This might only work for Android, but my app is currently only for Android anyway.

**Comment by BatteryAcid** [comment]
I am currently facing a similar problem, I was thinking to take the last 10 digits of the phone number then insert wildcards like 555%666%7777.  The underlying Android code will surround the search text with %.  This is definitely not ideal but would work for US phone numbers.  This does NOT work for iOS.  

After working with the current state of this plugin for the last 6 months (it's deprecated and not maintained) I would avoid using it unless you're doing something simple.  For updating contacts it's very buggy and required a ton of work arounds/hacks to get functional.  

Good luck!

**Comment by andersborgabiro** [comment]
I didn't know about the %xxxx% thing. Skipping (extra) %xxxx% in my code worked fine. I still do x%x%x%x... though.

Is there any trustworthy and maintained plugin that's might have solved number search better?

Clearly, the call manager (whether Android or iOS) has no problem finding numbers, so there's a method somewhere in the system, but maybe not accessible via API.

**Comment by BatteryAcid** [comment]
> Is there any trustworthy and maintained plugin that's might have solved number search better?

I'm not aware of any such plugin.  

Right, I think your solution should work fine for Android, and if you're saving phone numbers on iOS, I would suggest making sure it conforms to the standard `(xxx) xxx-xxxx`  otherwise the search functionality may not hit on the numbers.  I don't think the underlying cordova-contacts code matches the different formats for you.

**Comment by andersborgabiro** [comment]
I use an SMS reception module that doesn't work for iOS, so that's not an option anyway.

Thanks.

**Comment by timbru31** [comment]
We are archiving this repository following [Apache Cordova's Deprecation Policy](https://cordova.apache.org/deprecation_policy.html). We will not continue to work on this repository. Therefore all issues and pull requests are being closed. Thanks for your contribution.
