### ISSUE TITLE
displayName:Null for android and ios

### ISSUE THREAD

**Issue by Tarikul-islam-shazan** [apache/cordova-plugin-contacts#217]
**Device**
Android 9.1 ,iOS 13.1.2
[console image](https://ibb.co/5Gdhz6V)

**Problem**
Contact name is not displayed properly

**Comment by timbru31** [comment]
1. See https://github.com/apache/cordova-plugin-contacts#ios-quirks-1 for iOS
2. Sadly, this plugin is deprecated
3. Please follow the issue template

Thanks

**Comment by Tarikul-islam-shazan** [comment]
This problem has already been solved.
'contact.name' can be used.
