### ISSUE TITLE
Support multiple find contact inside a Loop

### ISSUE THREAD

**Issue by Elyft** [apache/cordova-plugin-contacts#219]
I know this plugin is obsolete but I would like to know if anyone has ever tried to search for elements with contact.find() in a for loop on a phone number array whose names we would like to return. I have tried but the results obtained are not complete

**Comment by acedigibits** [comment]
@Elyft it is because the process is asynchronous. i tried the same with for loop and failed. instead of for loop i looped it back to original function onsuccess with a global counter in the original main loop function. This gave complete result. 

Hope this answers your query.

**Comment by Elyft** [comment]
@acedigibits  i don't really understand what you say. can you please give me a little snippet?thank you

**Comment by acedigibits** [comment]
var main_counter=0, global_data;
function main_loop(){
if(main_counter<5){
contact.find(,onsuccess, onerror);
}else{
//your complete data
}
}
function onsuccess(){
main_counter++;
//global_data merge
main_loop();
}

**Comment by Elyft** [comment]
thank you for your snippet, but i'm not sure that it can fit yo my need let me show you my code
```javascript
module.exports = (...arrayToSearch)=>{
    return new Promise((resolve)=>{
        function getNameWithNumber(value){
            return new Promise((resolve)=>{
                function onSuccess(contacts) {
                    console.log(value)
                    resolve(contacts);
                };

                function onError(contactError) {
                    console.log(contactError)
                };

                const options = new ContactFindOptions();
                options.filter = value.address;
                options.multiple = true;
                options.hasPhoneNumber = true;
                const fields = ["*"];
                navigator.contacts.find(fields, onSuccess, onError, options);
                
            });
        }

        function getAllNames(...arrayToSearch){
          return Promise.all(arrayToSearch.map(getNameWithNumber)).then((value)=>{
           console.log(value)
          });
        }
        getAllNames(...arrayToSearch);
    });
};
```
Where arrayToSearch is an array of numbers to search

**Comment by acedigibits** [comment]
`module.exports = (...arrayToSearch)=>{
    return new Promise((resolve)=>{
		let main_counter=0, contacts_merge=[];
        function getNameWithNumber(value){
            return new Promise((resolve)=>{
                function onSuccess(contacts) {
                    console.log(value);
					if(main_counter>=5)
                    resolve(contacts);
					else{
						main_counter++;
						contacts_merge.push(contacts);
						main_loop();
					}
                };

                function onError(contactError) {
                    console.log(contactError)
                };
				
				function main_loop(){
					const options = new ContactFindOptions();
                options.filter = value.address;
                options.multiple = true;
                options.hasPhoneNumber = true;
                const fields = ["*"];
                navigator.contacts.find(fields, onSuccess, onError, options);
				}

                main_loop();
                
            });
        }

        function getAllNames(...arrayToSearch){
          return Promise.all(arrayToSearch.map(getNameWithNumber)).then((value)=>{
           console.log(value)
          });
        }
        getAllNames(...arrayToSearch);
    });
};`

**Comment by acedigibits** [comment]
you can check my app, where i have written loop and shown loading bar to indicate progress...

[https://play.google.com/store/apps/details?id=com.acedb.bulkcontactcreate](https://play.google.com/store/apps/details?id=com.acedb.bulkcontactcreate)

**Comment by timbru31** [comment]
We are archiving this repository following [Apache Cordova's Deprecation Policy](https://cordova.apache.org/deprecation_policy.html). We will not continue to work on this repository. Therefore all issues and pull requests are being closed. Thanks for your contribution.
