### ISSUE TITLE
No way to display single contact that I just added with this plugin?

### ISSUE THREAD

**Issue by kotran88** [apache/cordova-plugin-contacts#220]
Hello 
I thought when I add new contact, 
it should make open native contact app from phone, than show it to user notifying that "hey! I added succesfully!" 

but no way. I think there's no way of doing it...
pickContract is the one that just Open contact app not specifying certain one. 

How can I open contact app with a single one

**Comment by timbru31** [comment]
We are archiving this repository following [Apache Cordova's Deprecation Policy](https://cordova.apache.org/deprecation_policy.html). We will not continue to work on this repository. Therefore all issues and pull requests are being closed. Thanks for your contribution.
