### ISSUE TITLE
App Crash after save the new contact in Android 9

### ISSUE THREAD

**Issue by juanludukeboss** [apache/cordova-plugin-contacts#222]
When I try to save the new contact in Android 9, the App crash always after insert the contact. There is permissions for READ and WRITE in AndroidManifest.xml

Here, the code:
                
```
var myContact = navigator.contacts.create({
      displayName: 'Test',
       phoneNumbers: [{
              'type'  : 'phone',
              'value' : '99999999'
       }],
        emails: [{
              'type': 'email',
              'value': 'test@test.com'
       }]
}); 
myContact.save();
```

The code is very simple and save the contact perfectly in my Android phone, but the problem is that the App Crash after save.

Anyone know what the problem may be and could you help me ??

Thanks.

**Comment by SupriyaLakamsani** [comment]
I am also getting same issue for my application. 
@juanludukeboss : U found any solution?

**Comment by juanludukeboss** [comment]
@SupriyaLakamsani Since Android 8, the permission system changes to be able to work with the contacts, because if you try to save or delete a contact, you have to have read and write permissions (both), it was not only worth the write permission as before this Android version. This caused that when saving a contact, the App would crash and close automatically because it lacked read permission. The solution is to modify the file found in the contacts plugin, in the directory: "src / android / ContactManager.java"

The solution is in the commit: https://github.com/apache/cordova-plugin-contacts/pull/221/commits/d6f42ebfcb8b9db43204c5df03d8d98f385aedfe

I hope that this help you. For me is working ok in Android 10.
