### ISSUE TITLE
Localized Phone Label (iOS)

### ISSUE THREAD

**Issue by stranger26** [apache/cordova-plugin-contacts#223]
# Bug Report

### What is expected to happen?
Imported contact with custom label should display 'label'

### What does actually happen?
Imported contact with custom label displayed as '_$!<Label>!$_'

## Information

Look at the label 'school'
[Testing.vcf.zip](https://github.com/apache/cordova-plugin-contacts/files/4643242/Testing.vcf.zip)

[Stackoverflow Thread](https://stackoverflow.com/questions/35501642/fetch-localized-phone-label-using-contacts-frameworks) on similar issue

### Environment, Platform, Device

iOS 13

### Version information

[Outsystems Contacts Cordova](https://github.com/OutSystems/cordova-plugin-contacts)

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by timbru31** [comment]
We are archiving this repository following [Apache Cordova's Deprecation Policy](https://cordova.apache.org/deprecation_policy.html). We will not continue to work on this repository. Therefore all issues and pull requests are being closed. Thanks for your contribution.
