### ISSUE TITLE
App crashed

### ISSUE THREAD

**Issue by basitraza339** [apache/cordova-plugin-contacts#224]
This plugin crashed app android version 8 but contact is save correctly.

**Comment by abhaysofttech** [comment]
Any Solution on it

**Comment by basitraza339** [comment]
This plugin has broken due to a change in the way Android handles permissions in 8.0 (https://developer.android.com/about/versions/oreo/android-8.0-changes#o-pri).

Basically: in the past requesting the contact write permission would also give you the contact read permission, but now you have to request both if you want to do both (but it will only ask the user once). The reason the save function was crashing the app was because it was writing the contact and then trying to read it back when it only had the write permission.

I've forked the repository and updated the ContactManager.java file to work with Android 8.0: https://github.com/duncan-c/cordova-plugin-contacts/blob/master/src/android/ContactManager.java

You can simply overwrite your ContactManager.java file in the plugins/cordova-plugin-contacts/src/android directory and then force ionic to recompile the plugin by removing and then re-adding the android platform:

`
ionic platform rm android
ionic platform add android
`

**Comment by AliMohammad93** [comment]
like @basitraza339 said it's read permission issue on new android version 
so i used this plugin [cordova-plugin-android-permissions](https://github.com/NeoLSN/cordova-plugin-android-permissions#readme) to ask first for read permission then save the contanct 

permissions.requestPermission(permissions.READ_CONTACTS,() => {

         let contact = navigator.contacts.create();

         contact.displayName = 'Ali'

        contact.save( console.log('contact has been saved successfully '), console.log('contact has not been saved '););

},null)

**Comment by timbru31** [comment]
We are archiving this repository following [Apache Cordova's Deprecation Policy](https://cordova.apache.org/deprecation_policy.html). We will not continue to work on this repository. Therefore all issues and pull requests are being closed. Thanks for your contribution.
