### ISSUE TITLE
Possible deadlock in iOS queue management code

### ISSUE THREAD

**Issue by vmdominguez-usaa** [apache/cordova-plugin-contacts#225]
### Issue Type

- [x] Bug Report
- [ ] Feature Request
- [ ] Support Question

## Description
While performing regression testing with the iOS 14 beta, I discovered that my app would crash when attempting to remove a contact. After doing some digging, it appears to be caused by potentially unnecessary calls `dispatch_sync`.

## Information

While troubleshooting, I came upon [this StackOverflow answer](https://stackoverflow.com/a/10998307), which indicates that calling `dispatch_sync` targeting the current queue is a no-no. Through debugging my app, I discovered that this is indeed the scenario under which my app was crashing. It does not appear to crash on devices with iOS 13.

I believe I confirmed the source of the problem by changing the code in `CDVContacts.m` (`createAddressBook`) from
```objc
            dispatch_sync(dispatch_get_main_queue(), ^{
                if (error) {
                    workerBlock(NULL, [[CDVAddressBookAccessError alloc] initWithCode:UNKNOWN_ERROR]);
                } else if (!granted) {
                    workerBlock(NULL, [[CDVAddressBookAccessError alloc] initWithCode:PERMISSION_DENIED_ERROR]);
                } else {
                    // access granted
                    workerBlock(addressBook, [[CDVAddressBookAccessError alloc] initWithCode:UNKNOWN_ERROR]);
                }
            });
```
to
```objc
        dispatch_block_t onMain = ^{
            if (error) {
                workerBlock(NULL, [[CDVAddressBookAccessError alloc] initWithCode:UNKNOWN_ERROR]);
            } else if (!granted) {
                workerBlock(NULL, [[CDVAddressBookAccessError alloc] initWithCode:PERMISSION_DENIED_ERROR]);
            } else {
                // access granted
                workerBlock(addressBook, [[CDVAddressBookAccessError alloc] initWithCode:UNKNOWN_ERROR]);
            }
        };
        
        if ([NSThread isMainThread]) {
            onMain();
        } else {
            // callback can occur in background, address book must be accessed on thread it was created on
            dispatch_sync(dispatch_get_main_queue(), onMain);
        }
```
After I made this change locally and re-ran the app, the contact was successfully removed.

### Command or Code

`Contact.remove` from @ionic-native/contacts

### Environment, Platform, Device

crashed on iPad Pro: iPadOS 14 beta 2
did not crash on iPhoone XS iOS 13.6

### Version information

Cordova: 9
cordova-ios: 5.1.1
cordova-plugin-contacts: 3.0.1
Ionic: 3
@ionic-native/contacts: 4.1.0

## Checklist

- [x] I searched for already existing GitHub issues about this
- [ ] I updated all Cordova tooling to their most recent version (this is an enterprise app for my employer -- our app stack is outdated)
- [x] I included all the necessary information above

**Comment by anujraghuvanshi** [comment]
Even I am getting crash when it asks for initial permissions.

**Comment by timbru31** [comment]
We are archiving this repository following [Apache Cordova's Deprecation Policy](https://cordova.apache.org/deprecation_policy.html). We will not continue to work on this repository. Therefore all issues and pull requests are being closed. Thanks for your contribution.
