### ISSUE TITLE
Ios-9 : AddressBook is deprecated. Consider migrating to Contacts/ContactsUI. in ionic 4/5

### ISSUE THREAD

**Issue by Shubhasis10** [apache/cordova-plugin-contacts#226]
warning: AddressBook is deprecated. Consider migrating to Contacts instead.
  warning: AddressBookUI is deprecated. Consider migrating to ContactsUI instead

when I'm go to build for ios device showing  **AddressBook is deprecated** how to resolve it ?

**Comment by EinfachHans** [comment]
If you only need the find method, you can use my Plugin for this: https://github.com/EinfachHans/cordova-plugin-contacts-x

i created it, because this one is deprecated and uses **AddressBook**... If you have any problems, feel free to open an issue there 😊

**Comment by Shubhasis10** [comment]
Cannot read property 'requestPermission' of undefined
TypeError: Cannot read property 'requestPermission' of undefined

**Comment by timbru31** [comment]
We are archiving this repository following [Apache Cordova's Deprecation Policy](https://cordova.apache.org/deprecation_policy.html). We will not continue to work on this repository. Therefore all issues and pull requests are being closed. Thanks for your contribution.
