### ISSUE TITLE
App crash in android 10 

### ISSUE THREAD

**Issue by yashp98** [apache/cordova-plugin-contacts#227]
# Bug Report

## Problem
i have a app. from that app we can add ,remove and update contact in phone system when i try to create contact it is working but when i try to update contact it is keep crashing app . i aslo add read and write permission in save and remove but solution is still not work 
## Checklist

- [ ] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

**Comment by dromeroDev** [comment]
Same issue here

**Comment by EinfachHans** [comment]
Can you check if you have this with my Contacts Plugin aswell? https://github.com/EinfachHans/cordova-plugin-contacts-x

**Comment by yashp98** [comment]
@dromeroDev yes use this https://github.com/EinfachHans/cordova-plugin-contacts-x plugin and  load contacts, edit ,save ,  and delete work fine without crash in android and ios

**Comment by jmosqueda1987** [comment]
You solved your problem with android 10?. Regards

**Comment by timbru31** [comment]
We are archiving this repository following [Apache Cordova's Deprecation Policy](https://cordova.apache.org/deprecation_policy.html). We will not continue to work on this repository. Therefore all issues and pull requests are being closed. Thanks for your contribution.
