### ISSUE TITLE
Not able to fetch newly added contacts and contact last updated timestamp

### ISSUE THREAD

**Issue by tojopaul** [apache/cordova-plugin-contacts#233]
# Bug Report
After sync the contact to server. If i add a new contact in phone.not able to find it. Do we have any solution to find the newly add contact or last updated timestamp?

**Comment by timbru31** [comment]
We are archiving this repository following [Apache Cordova's Deprecation Policy](https://cordova.apache.org/deprecation_policy.html). We will not continue to work on this repository. Therefore all issues and pull requests are being closed. Thanks for your contribution.
